name: streaming

services:
  postgres:
    image: "postgres:16.3-alpine3.20"
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
    restart: always

  frontend:
    build: .
    ports:
      - 3002:3000
    depends_on:
      - postgres
    restart: always

  srs:
    image: ossrs/srs:5
    ports:
      - 1935:1935
      - 8088:8088
    volumes:
      - ./srs.conf:/usr/local/srs/conf/docker.conf
      - ./certificates:/usr/local/srs/conf
    depends_on:
      - frontend
    restart: always
