name: streaming

services:
  postgres:
    image: "postgres:16.3-alpine3.20"
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
    restart: always

  frontend:
    build: ./nextjs
    depends_on:
      - postgres
    env_file: .env
    restart: always

  socketio:
    build: ./socketio
    depends_on:
      - frontend
    ports:
      - 4000:4000
    restart: always

  srs:
    image: ossrs/srs:5
    ports:
      - 8080:8080
      - 1935:1935
    volumes:
      - ./srs.conf:/usr/local/srs/conf/docker.conf
    depends_on:
      - frontend
    restart: always

  caddy:
    image: caddy:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - frontend
      - socketio
      - srs
    restart: always
