name: streaming

services:
  postgres:
    image: "postgres:16.3-alpine3.20"
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
    restart: always

  frontend:
    build: /nextjs
    ports:
      - 3000:3000
    depends_on:
      - postgres
    env_file: .env
    restart: always

  socketio:
    build: /socketio
    ports:
      - 4000:4000
    depends_on:
      - frontend
    restart: always

  srs:
    image: ossrs/srs:5
    ports:
      - 1935:1935
      - 8080:8080
    volumes:
      - ./srs.conf:/usr/local/srs/conf/docker.conf
    depends_on:
      - frontend
    restart: always
